In [1]:
import torch
import torch 
import numpy as np
from numpy import meshgrid
from datasets import dataset_dict

In [50]:
def prepare_data():
    dataset = dataset_dict['blender_shadows']
    kwargs = {'root_dir': '../datasets/volumetric/results_500/',
              'img_wh': (400,400), 
              'hparams': None,
              }
    return dataset(split='val', **kwargs)

In [51]:
train_dataset = prepare_data()

Training Image size: (400, 400)


In [52]:
from torch.utils.data import DataLoader
loader = DataLoader(train_dataset, shuffle=False, num_workers=4, batch_size=1, pin_memory=True)
loader = iter(loader)

In [53]:
sample = next(loader)
sample

{'rays': tensor([[[-47.8855,  30.9148,  98.1950,  ...,  -0.7324,   1.0000, 150.0000],
          [-47.8855,  30.9148,  98.1950,  ...,  -0.7325,   1.0000, 150.0000],
          [-47.8855,  30.9148,  98.1950,  ...,  -0.7327,   1.0000, 150.0000],
          ...,
          [-47.8855,  30.9148,  98.1950,  ...,  -0.9296,   1.0000, 150.0000],
          [-47.8855,  30.9148,  98.1950,  ...,  -0.9294,   1.0000, 150.0000],
          [-47.8855,  30.9148,  98.1950,  ...,  -0.9293,   1.0000, 150.0000]]]),
 'rgbs': tensor([[[0.9137, 0.7490, 0.9647],
          [0.9412, 0.7725, 0.9412],
          [0.9294, 0.7765, 0.9333],
          ...,
          [1.0000, 1.0000, 1.0000],
          [1.0000, 1.0000, 1.0000],
          [1.0000, 1.0000, 1.0000]]]),
 'c2w': tensor([[[-5.4239e-01,  7.2659e-01, -4.2176e-01, -4.7886e+01],
          [-8.4013e-01, -4.6909e-01,  2.7228e-01,  3.0915e+01],
          [ 1.4901e-08,  5.0201e-01,  8.6486e-01,  9.8195e+01]]]),
 'valid_mask': tensor([[ True,  True,  True,  ..., False, Fals

In [55]:
from PIL import Image
from torchvision import transforms
T = transforms.ToTensor()

depth = Image.open("r_0_depth_0093.png")
depth = depth.resize((400,400))
depth = T(depth)

In [2]:
from camera import Camera

In [15]:
fov = 5.60622567406272 # 0.0978470966219902 rad 
cam = Camera(fov, (800,800))
cam.camera

tensor([[ 1.0000e+00,  0.0000e+00, -4.0000e+02],
        [ 0.0000e+00, -1.0000e+00,  4.0000e+02],
        [ 0.0000e+00,  0.0000e+00, -8.1695e+03]])

In [16]:
cam.set_pose_using_blender_matrix(c2w[:3, :4])

In [19]:
cam.camera, cam.eye_pos

(tensor([[ 8.8843e-01,  3.4820e-01, -2.9378e+03],
         [ 4.5886e-01, -6.5693e-01,  4.9662e+03],
         [ 1.1830e-02, -6.6873e-01, -5.8109e+03]]),
 tensor([ 200., -400.,  500.]))

In [4]:
import json
file = "../datasets/volumetric/results_500_v2/transforms.json"
with open(file) as f:
    data = json.load(f)

data.keys()

dict_keys(['camera_angle_x', 'light_camera_angle_x', 'light_camera_transform_matrix', 'frames'])

In [11]:
fov = data['light_camera_angle_x']
c2w = np.array(data['light_camera_transform_matrix'])
fov, c2w[:3, :4]

(0.0978470966219902,
 array([[ 8.88431907e-01, -3.48196030e-01,  2.99056917e-01,
          2.00000000e+02],
        [ 4.58855867e-01,  6.56932235e-01, -5.98198533e-01,
         -4.00000000e+02],
        [ 1.18302405e-02,  6.68729782e-01,  7.43453681e-01,
          5.00000000e+02]]))

In [18]:
c2w[:3, :4]

array([[ 8.88431907e-01, -3.48196030e-01,  2.99056917e-01,
         2.00000000e+02],
       [ 4.58855867e-01,  6.56932235e-01, -5.98198533e-01,
        -4.00000000e+02],
       [ 1.18302405e-02,  6.68729782e-01,  7.43453681e-01,
         5.00000000e+02]])